#!/usr/bin/env php
<?php
/**
 *
 */
#ini_set('display_errors', 1);
#error_reporting(-1);

require_once __DIR__.'/vendor/autoload.php';

// Aura CLI classes
use Aura\Cli\CliFactory;
use Aura\Cli\Context\OptionFactory;
use Aura\Cli\Help;
use Aura\Cli\Status;

// Own classes
use Suncron\Logger;
use Suncron\Dipper;
use Suncron\TimesParser;

$cli     = new CliFactory;
$context = $cli->newContext($GLOBALS);
$logger  = new Logger($cli->newStdio());

$version = PHP_EOL
         . '<<bold yellow>>* * *  SunCron/PHP v'.file_get_contents(__DIR__.'/.version').'  * * *<<reset>>'
         . PHP_EOL;

/**
 * Command line options
 */
$options = [
    's,stdout'  => 'Write cron entries to stdout.',
    'o,output:' => 'Write cron entries to file <value>.',
    't,test'    => 'Test mode, only analyse configuration',
    'v*'        => 'Verbosity level, multiple use increases verbosity',
    'help'      => 'This help',
];

$getopt = $context->getopt(array_keys($options));

$error = false;

if ($getopt->hasErrors()) {
    $error = $getopt->getErrors();
    foreach ($error as $err) {
        $logger->error($err->getMessage());
    }
    $logger->err();
};

$showHelp = $getopt->get('--help');

if (!$showHelp && '' == $conf_file = $getopt->get(1)) {
    $error = true;
    $logger->error('Missing configuration file!');
    $logger->err();
}

/**
 * Usage
 */
if ($error || $showHelp) {
    $logger->err(0, $version);

    $help = new Help(new OptionFactory);

    $help->setSummary('Create crontabs relative to sunrise and sunset.');
    $help->setUsage('[options] <config file>');
    $help->setOptions($options);
    $help->setDescr(
    	'See <<bold>>dist/*.yaml<<reset>> for examples and details'.PHP_EOL
       .'    Github: https://github.com/K-Ko/suncron-php'
    );
    $logger->err(0, $help->getHelp($getopt->get(0)));

    exit(isset($errors) ? Status::FAILURE : Status::SUCCESS);
}

$test    = $getopt->get('-t', false);
$verbose = count($getopt->get('-v', []));

if ($test) {
    $logger->err(0, $version);
    $logger->err(0, '<<bold>><<green>>TEST mode, don\'t write crontab'.PHP_EOL);
    $verbose++;
}

$logger->setLevel($verbose);

/**
 *
 */
try {

    $logger->err(2, 'Config file', $conf_file);

    $conf = Dipper::parseFile($conf_file);

    $loc = array_merge(
    	[ 'Timezone' => file_get_contents('/etc/timezone'), 'Zenith' => 90+50/60 ],
    	$conf['Location']
    );

    $TimesParser = new TimesParser(
        $loc['Latitude'], $loc['Longitude'], $loc['Timezone'], $loc['Zenith']
    );

    $logger->err(1, 'Sunrise - Sunset', $TimesParser->getSunrise(), '-', $TimesParser->getSunset());

    $cron = [];

    // Analyse rules
    foreach ($conf['Rules'] as $idx=>$rule) {

        $rule = array_merge(
            [ 'if' => true, 'then' => null, 'else' => null, 'cron' => null ],
            $rule
        );

        $logger->err(1, str_repeat('-', 60));
        $logger->err(1, implode(' | ', $rule));
        $logger->err(1, 'IF', $rule['if']);

        $res = $TimesParser->parse($rule['if']);
        foreach ($TimesParser->getDebug() as $d) {
        	$logger->err($d[0], 'IF parsed', $d[1]);
        }
        $logger->err(1, 'IF result', ['false','true'][$res]);

        if (
            ( $res && $rule['then'] && $time = $TimesParser->parse($rule['then'])) ||
            (!$res && $rule['else'] && $time = $TimesParser->parse($rule['else']))
        ) {
            $label = ['ELSE','THEN'][$res];

            foreach ($TimesParser->getDebug() as $d) {
            	$logger->err($d[0], $label, $d[1]);
            }
            $logger->err(3, $label, date('H:i', $time));

            $cmd = date('i H', $time) . ' ' . str_replace(
                [ '$sunrise_ts', '$sunset_ts', '$sunrise', '$sunset' ],
                [ $TimesParser->getSunriseInt(), $TimesParser->getSunsetInt(),
                  $TimesParser->getSunrise(), $TimesParser->getSunset() ],
                $rule['cron']
            );
            $logger->err(1, 'Cron', $cmd);
            $cron[] = $cmd;
        }
    }

    if (count($cron)) {

        $logger->err(1, str_repeat('-', 60));

        if ($test || $getopt->get('-s')) {
            // Output crontab to stdout
            $output = '-';
        } else {
            $output = $getopt->get('-o');
            if ('' == $output = $getopt->get('-o')) {
                // Build file name from config file
                $output = pathinfo($conf_file);
                $output = '/etc/cron.d/'.str_replace('.', '_', $output['filename']);
            }
        }

        // Add header lines to cron file
        $cron = implode(PHP_EOL, array_merge(
            ['#', '# WARNING - this file is automatically generated, changes will be lost',
             '#', '# '.realpath($getopt->get(0)).' '.realpath($conf_file), '#'],
            $cron
        ));

        if ($output == '-') {
            $logger->out(0, '<<blue>>'.$cron);
        } elseif ($bytes = @file_put_contents($output, $cron)) {
            $logger->err(1, '<<green>>Wrote '.$bytes.' Bytes to \''.$output.'\'');
        } else {
            throw new Exception('Can\'t write \''.$output.'\', must run as root');
        }
    }

} catch (Exception $e) {
    $logger->error($e->getMessage());
    exit(Status::FAILURE);
}

exit(Status::SUCCESS);
